from Antylope import Antylope
from Fox import Fox
from Sheep import Sheep
from Turtle import Turtle
from Wolf import Wolf
from Grass import Grass
from Guarana import Guarana
from SosnowskiBarszcz import SosnowskiBarszcz
from Belladonna import Belladonna
from Human import Human
from Dandelion import Dandelion
from CyberSheep import CyberSheep